function safeSetText(id,text){const el=document.getElementById(id);if(el)el.textContent=text}let currentStage=1;let workflowState=null;
document.addEventListener('DOMContentLoaded',()=>{fetch('/get_state').then(res=>res.json()).then(state=>{workflowState=state;updateStageDisplay()})});
const projectUploadArea=document.getElementById('projectUploadArea'),projectFile=document.getElementById('projectFile'),projectSubmitBtn=document.getElementById('projectSubmitBtn'),projectForm=document.getElementById('projectForm');
projectUploadArea.addEventListener('click',()=>{projectFile.click()});
projectFile.addEventListener('change',e=>{const file=e.target.files[0];if(file){const placeholder=projectUploadArea.querySelector('.upload-placeholder');placeholder.innerHTML='<span class="upload-icon">📄</span><p>'+file.name+'</p>';projectSubmitBtn.disabled=false}});
projectUploadArea.addEventListener('dragover',e=>{e.preventDefault();projectUploadArea.style.background='#f0f4ff'});
projectUploadArea.addEventListener('dragleave',()=>{projectUploadArea.style.background='transparent'});
projectUploadArea.addEventListener('drop',e=>{e.preventDefault();projectUploadArea.style.background='transparent';const file=e.dataTransfer.files[0];if(file){projectFile.files=e.dataTransfer.files;const placeholder=projectUploadArea.querySelector('.upload-placeholder');placeholder.innerHTML='<span class="upload-icon">📄</span><p>'+file.name+'</p>';projectSubmitBtn.disabled=false}});
projectForm.addEventListener('submit',async e=>{e.preventDefault();const file=projectFile.files[0];if(!file){alert('请选择文件');return}projectSubmitBtn.disabled=true;projectSubmitBtn.textContent='处理中...';const formData=new FormData();formData.append('file',file);try{const response=await fetch('/upload_project',{method:'POST',body:formData});const result=await response.json();if(result.success){safeSetText('courseContent',result.data.course_content);document.getElementById('courseResult').style.display='block';renderTasks(result.data.student_tasks);document.getElementById('tasksResult').style.display='block';document.getElementById('status1').textContent='已完成';document.getElementById('tab1').classList.add('completed');fetch('/get_state').then(res=>res.json()).then(state=>{workflowState=state})}else{alert('执行失败: '+result.error)}}catch(error){alert('请求失败: '+error.message)}finally{projectSubmitBtn.disabled=false;projectSubmitBtn.textContent='生成教学材料和任务'}});
function renderTasks(tasks){const tasksList=document.getElementById('tasksList');tasksList.innerHTML=tasks.map(task=>'<div class="task-item"><div class="task-id">'+task['任务ID']+'</div><div class="task-name">'+task['任务名称']+'</div><div class="task-desc">'+task['任务描述']+'</div><div class="task-meta"><span>难度: '+task['难度']+'</span> | <span>截止时间: '+task['截止时间']+'</span></div></div>').join('')}
function goToStage2(){currentStage=2;updateStageDisplay();document.getElementById('taskSelect').innerHTML='<option value="">请选择任务</option>'+workflowState.student_tasks.map(task=>'<option value="'+task['任务ID']+'">'+task['任务ID']+' - '+task['任务名称']+'</option>').join('')}
const homeworkUploadArea=document.getElementById('homeworkUploadArea'),homeworkFile=document.getElementById('homeworkFile'),homeworkSubmitBtn=document.getElementById('homeworkSubmitBtn'),homeworkForm=document.getElementById('homeworkForm'),taskSelect=document.getElementById('taskSelect');
homeworkUploadArea.addEventListener('click',()=>{homeworkFile.click()});
homeworkFile.addEventListener('change',e=>{const file=e.target.files[0];if(file){const placeholder=homeworkUploadArea.querySelector('.upload-placeholder');placeholder.innerHTML='<span class="upload-icon">📝</span><p>'+file.name+'</p>';checkHomeworkForm()}});
taskSelect.addEventListener('change',checkHomeworkForm);
function checkHomeworkForm(){const file=homeworkFile.files[0];const taskId=taskSelect.value;homeworkSubmitBtn.disabled=!file||!taskId}
homeworkUploadArea.addEventListener('dragover',e=>{e.preventDefault();homeworkUploadArea.style.background='#f0f4ff'});
homeworkUploadArea.addEventListener('dragleave',()=>{homeworkUploadArea.style.background='transparent'});
homeworkUploadArea.addEventListener('drop',e=>{e.preventDefault();homeworkUploadArea.style.background='transparent';const file=e.dataTransfer.files[0];if(file){homeworkFile.files=e.dataTransfer.files;const placeholder=homeworkUploadArea.querySelector('.upload-placeholder');placeholder.innerHTML='<span class="upload-icon">📝</span><p>'+file.name+'</p>';checkHomeworkForm()}});
homeworkForm.addEventListener('submit',async e=>{e.preventDefault();const file=homeworkFile.files[0];const taskId=taskSelect.value;if(!file||!taskId){alert('请选择任务和文件');return}homeworkSubmitBtn.disabled=true;homeworkSubmitBtn.textContent='提交中...';const formData=new FormData();formData.append('file',file);formData.append('task_id',taskId);try{const response=await fetch('/submit_homework',{method:'POST',body:formData});const result=await response.json();if(result.success){alert('作业提交成功！');homeworkForm.reset();homeworkUploadArea.querySelector('.upload-placeholder').innerHTML='<span class="upload-icon">📝</span><p>点击或拖拽作业文件到此处</p>';checkHomeworkForm();fetch('/get_state').then(res=>res.json()).then(state=>{workflowState=state;renderSubmissions(state.submissions)})}else{alert('提交失败: '+result.error)}}catch(error){alert('请求失败: '+error.message)}finally{homeworkSubmitBtn.disabled=false;homeworkSubmitBtn.textContent='提交作业'}});
function renderSubmissions(submissions){const submissionsList=document.getElementById('submissionsList');if(submissions.length===0){submissionsList.innerHTML='<p style="text-align:center;color:#999;">暂无提交</p>';return}submissionsList.innerHTML=submissions.map(sub=>'<div class="submission-item"><div class="submission-task">任务: '+sub.task_id+'</div><div class="submission-file">文件: '+sub.filename+'</div><div class="submission-time">提交时间: '+sub.submit_time+'</div></div>').join('');document.getElementById('submissionsResult').style.display='block'}
async function generateReport(){if(workflowState.submissions.length===0){alert('还没有提交任何作业');return}if(!confirm('确定要生成点评报告吗？')){return}try{const response=await fetch('/generate_report',{method:'POST'});const result=await response.json();if(result.success){safeSetText('reportContent',result.report);currentStage=3;updateStageDisplay();document.getElementById('status2').textContent='已完成';document.getElementById('tab2').classList.add('completed')}else{alert('生成失败: '+result.error)}}catch(error){alert('请求失败: '+error.message)}}
async function resetWorkflow(){if(!confirm('确定要开始新的工作流吗？所有数据将被清空。')){return}try{const response=await fetch('/reset_workflow',{method:'POST'});const result=await response.json();if(result.success){location.reload()}}catch(error){alert('重置失败: '+error.message)}}
function updateStageDisplay(){document.querySelectorAll('.stage-content').forEach(el=>{el.style.display='none'});document.querySelectorAll('.stage-tab').forEach((el,index)=>{el.classList.remove('active');if(index+1===currentStage){el.classList.add('active')}});const stageEl=document.getElementById('stage'+currentStage);if(stageEl){stageEl.style.display='block'}}
document.querySelectorAll('.stage-tab').forEach(tab=>{tab.addEventListener('click',()=>{const stage=parseInt(tab.dataset.stage);if(stage<=workflowState.stage){currentStage=stage;updateStageDisplay()}})});
